### ISSUE TITLE
Filter reporting improvements

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web-v3#21]
The filter reporting (obtained by clicking the warning sign) is possibly too basic. For example: filter Precambrian then add Cambrian then add carbonate. This filter is:

(age:Precambrian OR Cambrian) AND (lith:carbonate)

If I add sandstone... is this and/or? (it seems to be or) so filter is now:
(age:Precambrian OR Cambrian) AND (lith:carbonate OR sandstone)

**Comment by cambro** [comment]
Note that there would be some value potentially in actively showing the applied filter in the screen someplace (right below search bar, within search bar in gray?) rather than having to click and get an overarching popup.

**Comment by jczaplew** [comment]
I'll consider this done for now
