### ISSUE TITLE
GDD panel layout bugs in most views

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/web-v3#24]
![untitled](https://user-images.githubusercontent.com/6107153/47574016-483f3a80-d904-11e8-9a94-bf713a1ecc32.jpg)

**Comment by jczaplew** [comment]
I can't seem to replicate this one. Safari I'm assuming?

**Comment by jczaplew** [comment]
CSS had not been compiled on steno in a while. Fixed.
